---
- name: stop logstash service
  shell: |
    ps -ef |grep logstash|grep -v grep|awk '{print $2}'|xargs kill -9
  ignore_errors: true

- name: rm logstash directory
  file:
    path: "{{item}}"
    state: absent
  with_items: 
      - "{{elk.APP_DIR}}/logstash"
      - "{{elk.APP_DIR}}/logstash-{{elk.version}}.tar.gz"

- name: download logstash package
  shell:
    "wget {{logstash_url}}/logstash-{{elk.version}}.tar.gz"
  args:
    chdir: "{{elk.APP_DIR}}/"


- name: unarchive logstash package
  unarchive:
    src: "{{elk.APP_DIR}}/logstash-{{elk.version}}.tar.gz"
    dest: "{{elk.APP_DIR}}/"
    remote_src: yes
    mode: 0755

- name: rename logstash directory
  shell: |
    mv logstash-{{elk.version}}   logstash
  args:
    chdir: "{{elk.APP_DIR}}/"


- name: config logstash config files
  lineinfile:
    path: "{{elk.APP_DIR}}/logstash/config/logstash.yml"
    regexp: "^{{item.key}}"
    line: "{{item.key}}: {{item.value}}"
  with_items:
      - "{{logstash_config}}"


- name: cerate logstash rule sample
  template:
    src: logstash-sample.j2
    dest: "{{elk.APP_DIR}}/logstash/config/logstash-sample.conf"

- name: chown logstash directory
  file:
    path: "{{elk.APP_DIR}}/logstash"
    state: directory
    recurse: yes
    mode: 0755


- name: start  logstash service
  shell: |
    set -m;nohup ./bin/logstashd &
  args:
    chdir: "{{elk.APP_DIR}}/logstash"

